version: '3.9'

services:
  postgres_local:
    image: postgres:15
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5


  backend:
    image: 204803176565.dkr.ecr.eu-north-1.amazonaws.com/autoblog/backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      postgres_local:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: blog_db
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}

  frontend:
    image: 204803176565.dkr.ecr.eu-north-1.amazonaws.com/autoblog/frontend:latest
    container_name: frontend
    ports:
      - "80:5173"
    depends_on:
      - backend
    environment:
      - VITE_REACT_APP_BACKEND_URL=http://13.53.36.72:3000

volumes:
  postgres_data:
